### ISSUE TITLE
在某些遊戲裡能夠行走

### ISSUE THREAD

**Issue by aweertyu12** [gemilepus/Scriptboxie#3]
當我在楓之谷中嘗試使用該程式時，能夠正常使用除了上下左右之外的按鍵，有嘗試過使用record以及更換指令，但卻仍然無法使用左右鍵。

**Comment by gemilepus** [comment]
我幫你試了一下，是可以動的，
一般遊戲裡角色的操作都是用同樣的輸入，不過它這裡好像有點不一樣
<img src="https://github.com/gemilepus/Scriptboxie-test/blob/main/test/20230526%20key%20test.gif?raw=true" width="500"/>
