### ISSUE TITLE
Play / Step through the commands?

### ISSUE THREAD

**Issue by Snacko** [gemilepus/Scriptboxie#4]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It would be nice if we could 'step' through the commands, one at a time?  Add a hotkey for stepping through.

**Describe alternatives you've considered** 
Or, put a **>** 'Play' button next to each command?

**Additional context**
I'm using SB to automate Facebook Post Scheduling, and they keep moving things on the page & changing things.  So, I have to spend an hour fixing my script each month.  So, being able to 'Play' all or 1 command, would save a lot of testing to fix them..

**Comment by gemilepus** [comment]
Most of what kind of commands or situations require "play" it?

**Comment by Snacko** [comment]
For me, I mostly use the move command and it keeps changing. So I could
change its coordinates and click play and see if I have the coordinates
correct.

**Comment by gemilepus** [comment]
Have you ever used this feature? It displays the position of the mouse
![xy](https://github.com/gemilepus/Scriptboxie/assets/31269075/fae3ed82-b949-45ba-abba-6656260e0216)

**Comment by Snacko** [comment]
Yes, I use that to fix my move commands. But I have to run the whole script
to get to the command.

I recently found the option to run the script slowly in the edit mode.
That helps a lot.  But if it's easy to add a play btn on the move, and any
other commands where it makes sense, that would be nice.

Andy

**Comment by gemilepus** [comment]
Got it. I will think about ways to achieve it. :)

**Comment by Snacko** [comment]
Thanks, that would be great.

**Comment by gemilepus** [comment]
Now available in 1.5.7

**Comment by Snacko** [comment]
Awesome!!  And it works great!!

I wanted to donate to you via paypal, but when I click your link in the
app, it shows me this screen.  And I don't know what it means?  For all I
know, it might say to send you $1,000,000,000???


[image: Scriptboxie_240125-13.27.55.498.png]

Thanks!!

**Comment by gemilepus** [comment]
I can't seem to see your screen here, so I'm not sure what the problem is,
but you may via ko-fi and it should work
[ko-fi](https://ko-fi.com/gemilepus)

:)

**Comment by Snacko** [comment]
Your other paypal took me to paypal but it was in your local language..

But I was able to do it through ko-fi with paypal on that..
