### ISSUE TITLE
Moving the mouse pointer back to its original position after a macro operation

### ISSUE THREAD

**Issue by fhap** [gemilepus/Scriptboxie#5]
I used a language translator.
My English may be weird.

For example, the macro action is left click x100, y100.
If I start the macro at any position of the mouse pointer, the macro will remember it,
and is it possible to left click on x100,y100 and go back to the original position?

Now
![now](https://github.com/gemilepus/Scriptboxie/assets/156774225/b58235cb-ee1f-4907-9577-363d4486c696)

Want
![want](https://github.com/gemilepus/Scriptboxie/assets/156774225/abee6608-c142-4e51-bcf0-268f8561e6a4)

**Comment by gemilepus** [comment]
I  think this should help you.

{StartPostion_X},{StartPostion_Y}
<img width="450" alt="move" src="https://github.com/gemilepus/Scriptboxie/assets/31269075/1afcf607-2585-4f39-a2cf-f9e988b553e8">

**Comment by fhap** [comment]
![wow](https://github.com/gemilepus/Scriptboxie/assets/156774225/db6b4a95-25fd-4c51-8a4a-8c55b346bead)

That's what I wanted.
It works great.
Thank you so much.
