### ISSUE TITLE
Image matching is difficult.

### ISSUE THREAD

**Issue by fhap** [gemilepus/Scriptboxie#6]
Test image
![cap](https://github.com/gemilepus/Scriptboxie/assets/156774225/2c07fa3e-7c4e-4ff2-af0c-85259d04b545)

![CUT3_size](https://github.com/gemilepus/Scriptboxie/assets/156774225/1b79a9e1-4a53-4181-8686-0a82b77a3b78)  ==  ![CUT3](https://github.com/gemilepus/Scriptboxie/assets/156774225/f186a8fb-ca4f-4b26-877d-f536f6234128)

![CUT4_size](https://github.com/gemilepus/Scriptboxie/assets/156774225/e60d90dd-8a0b-4c45-bebe-a8db53ce1d49)  == ![CUT4](https://github.com/gemilepus/Scriptboxie/assets/156774225/288a93c1-4dcf-4598-a798-fb436e4c2f3a)

![Animation](https://github.com/gemilepus/Scriptboxie/assets/156774225/8b9ce9b5-b5f6-4fdc-a3e8-1ae68ac61b89)

What looks like the same thing to the human eye,
but looks different to a computer?

**Comment by gemilepus** [comment]
If their shapes have different lengths, then they are different to the computer. This situation can usually be handled by narrowing down the comparison range. 
For example, like this:
sample
![match](https://github.com/gemilepus/Scriptboxie/assets/31269075/9d8b0ecb-de02-4e93-9ac3-00c06652d5c5)
test
![image](https://github.com/gemilepus/Scriptboxie/assets/31269075/6ed70f72-d43b-44e9-b24a-4d6402b7b97a)

**Comment by fhap** [comment]
![Thank you!](https://github.com/gemilepus/Scriptboxie/assets/156774225/97144dc1-886c-4e50-880c-d7469698bd66)

Thanks for pointing me in the right direction.
I'll have to look into the conditions for my situation a bit more. :)
