### ISSUE TITLE
Is it possible to see the mouse position after a 'Match'?

### ISSUE THREAD

**Issue by fhap** [gemilepus/Scriptboxie#7]
Can I compare whether the mouse position is to the left or right of the {StartPostion_X} after 'Match'?

The program I use, RDWorks, doesn't use '-position' for virtual arrays, so I have to check if the reference point is on the left or right and then change it.

![lol](https://github.com/gemilepus/Scriptboxie/assets/156774225/99f64f05-9023-4ab5-9fa6-fe27c3e665a6)
![lol2](https://github.com/gemilepus/Scriptboxie/assets/156774225/e7f3ce4a-8f1c-48ac-81a4-47d5a506b7cf)

Although I can do it semi-automatically with the StartPosition you mentioned,
it would be nice to be able to fully automate it by checking left and right with 'Match'.

And I'm not English either, so I realize this in hindsight, but {StartPostion_X},{StartPostion_Y} seems to be a typo.
                                                                                                {StartPos"i"tion_X},{StartPos"i"tion_Y}

**Comment by gemilepus** [comment]
Currently, it is not possible to compare mouse positions, and it is expected to make it possible in the next version.
 
These typos will be corrected later. 
:)

**Comment by fhap** [comment]
Thank you so much.
It's still the best program for me.

**Comment by gemilepus** [comment]
Now available in 1.5.7
[more](https://github.com/gemilepus/Scriptboxie#default-functions--values)

**Comment by fhap** [comment]
![Thank you very much](https://github.com/gemilepus/Scriptboxie/assets/156774225/40a8ebf7-2bdc-4a48-8398-fba222712bd1)
(The working GIF is large(6MB) and takes a long time to load.)
When I saw the update, I jumped at the chance.
Thank you so, so, so much for making the program :)
I still can't stop 'Match' from running infinitely, but it's perfect for me.

**Comment by gemilepus** [comment]
You can upload scripts (.txt)
Let me confirm why it won't stop.

**Comment by fhap** [comment]
Test : ![cap](https://github.com/gemilepus/Scriptboxie/assets/156774225/e3a9c342-d6ff-4f87-8208-8c224cad7902)
Match : ![CUT](https://github.com/gemilepus/Scriptboxie/assets/156774225/b0a82f35-34f5-47db-a3a2-4a45f2e3e3bd)

If you try it with a test image, it works exactly 40 times.

However, in the program, the red box changes its appearance when it is selected.
![cap2](https://github.com/gemilepus/Scriptboxie/assets/156774225/24d9db29-dba8-4eb6-a569-3e91dacc12a1)

I think it's because the selected box appears and disappears when 'Match', and it thinks it's a new box.
Thank you for your consideration :)

[matchtest.txt](https://github.com/gemilepus/Scriptboxie/files/14058672/matchtest.txt)

**Comment by fhap** [comment]
My bad.
I left out the escape 'Jump'.

![cap3](https://github.com/gemilepus/Scriptboxie/assets/156774225/22c934bc-2f54-42f7-8559-f087ae6c5757)

It's working fine for now!
I think I just need to tweak the delay when copying and pasting. :)
